# Generated by Django 4.2.6 on 2023-11-21 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Degreeprogram',
            fields=[
                ('deg_name', models.CharField(max_length=40, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dept_name', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('room_no', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fac_id', models.IntegerField()),
                ('fac_name', models.CharField(max_length=40)),
                ('dept_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.department')),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sem_id', models.CharField(max_length=10)),
                ('sem_num', models.IntegerField()),
                ('reg_year', models.CharField(max_length=50)),
                ('sem_type', models.CharField(max_length=10)),
                ('deg_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.degreeprogram')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('Sub_code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('sub_title', models.CharField(max_length=40)),
                ('tcp', models.IntegerField()),
                ('reg_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='app.semester')),
                ('sem_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.semester')),
            ],
        ),
        migrations.CreateModel(
            name='TimetableData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_no', models.IntegerField()),
                ('fac_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.faculty')),
                ('sub_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='app.subject')),
                ('sub_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='app.subject')),
            ],
        ),
        migrations.AddField(
            model_name='faculty',
            name='sub_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.subject'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='sub_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fac_members', to='app.subject'),
        ),
        migrations.AddField(
            model_name='degreeprogram',
            name='dept_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.department'),
        ),
        migrations.AlterField(
            model_name='admin',
            name='fac_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.faculty'),
        ),
    ]
