# Generated by Django 4.2.6 on 2023-11-21 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_degreeprogram_department_faculty_semester_subject_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admin',
            options={'verbose_name_plural': '7. Admin'},
        ),
        migrations.AlterModelOptions(
            name='degreeprogram',
            options={'verbose_name_plural': '2. Degreeprograms'},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name_plural': '1. Departments'},
        ),
        migrations.AlterModelOptions(
            name='faculty',
            options={'verbose_name_plural': '5. Faculty'},
        ),
        migrations.AlterModelOptions(
            name='semester',
            options={'verbose_name_plural': '3. Semester'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name_plural': '4. Subject'},
        ),
        migrations.AlterModelOptions(
            name='timetabledata',
            options={'verbose_name_plural': '6. TimetableData'},
        ),
        migrations.RemoveField(
            model_name='department',
            name='room_no',
        ),
    ]
