# Generated by Django 4.2.6 on 2023-11-21 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_admin_options_alter_degreeprogram_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='sem_id',
            field=models.IntegerField(max_length=10),
        ),
    ]
