# Generated by Django 4.2.6 on 2023-11-21 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_semester_sem_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='sem_id',
            field=models.IntegerField(),
        ),
    ]
