# Generated by Django 4.2.6 on 2023-11-21 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_admin_id_remove_faculty_id_remove_semester_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='tcp',
            field=models.IntegerField(default=False),
        ),
    ]
